[package]
name = "simple_shader_builder_api"
version.workspace = true
edition.workspace = true
publish.workspace = true

[build-dependencies]
cargo-gpu = { workspace = true }

[lints]
workspace = true
